server:
  port: 8080 
  error:
    path: /error2

# thymeleaf
spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: html
    encoding: UTF-8
    content-type: text/html
    cache: false
# custom
  application:
    name: Bootstrap Spring Boot  
# h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password: 
# Security    
security:
  oauth2:
    client:
      clientId: 2645378639031574
      clientSecret: 036633fffe1bb8e281fd450c74eccdf2
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
sonar: 
   tests: src/test
 